language: node_js
node_js:
 - "node"
services:
 - mongodb
before_script:
 - sleep 5
 - mongo ds119059.mlab.com:19059/nokia-reservation -u root -p qwerty123
 - cd Backend && npm install
 - cd Frontend && npm install
after_success:
 - git config --global user.name "maciejjaskolski"
 - git config --global user.email "226242@student.pwr.wroc.pl"
 - git remote rm origin
 - git remote add origin "https://github.com/MaciejJaskolski/reservation_form.git"
 - cd Frontend && npm run deploy
